spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.50.185:3306/mybatisplus?characterEncoding=utf-8
    username: root
    password: root
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  #  控制台输出sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰 create_time
    map-underscore-to-camel-case: true


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
